apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-gitops-app-default
  namespace: openshift-gitops
spec:
  project: test-gitops-default
  source:
    repoURL: 'https://github.com/aladrocMatiner/poc-ksops.git'
    targetRevision: HEAD
    path: "./"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test-gitops-default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
