apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-gitops-00
  namespace: openshift-gitops-operator
spec:
  project: default
  source:
    repoURL: 'https://github.com/aladrocMatiner/poc-ksops.git'
    targetRevision: HEAD
    path: /
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test-gitops-00
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
